name: Test and Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the script
    steps:
      - run npm worker.js
      # TODO

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}